# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1atpSOAMxn07csYfDmIZejEJthVuq6Cdy
"""

!pip install flask-ngrok

from flask import Flask, render_template, request, jsonify
from flask_ngrok import run_with_ngrok

app = Flask(__name__)
run_with_ngrok(app)

@app.route('/')
def home():
    return render_template('index.html')

    @app.route('/evaluate', methods=['POST'])
    def evaluate():
        essay_text = request.form.get('essay', '')

                # Example: Simple word count evaluation
    feedback = f"Your essay has {len(essay_text.split())} words."

    return jsonify({"feedback": feedback})

    if __name__ == '__main__':
      app.run()